version: '3.8'

services:

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    depends_on:
      platform-core-service:
        condition: service_started
      background_job_worker:
        condition: service_started

  platform-core-service:
    container_name: platform-core-service
    build:
      context: .
      dockerfile: ./platform-core-service/Dockerfile
    ports: 
      - "8080:8080"
    volumes:
      - platform_core_upload:/var/www/uploads
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      background_job_worker:
        condition: service_started

  message-service: 
    container_name: message-service
    build:
      context: ./message-service
      dockerfile: Dockerfile
    env_file:
      - ./message-service/.env.production
    volumes:
      - message_service_upload:/var/www/Message-Upload
    depends_on:
      platform-core-service:
        condition: service_started   # ✅ only wait for start
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy

  notification-service: 
    container_name: notification-service
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    env_file:
      - ./notification-service/.env.production
    depends_on:
      platform-core-service:
        condition: service_started   # ✅ only wait for start
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy

  ai-worker:
    container_name: ai-worker
    environment:
      DATABASE_URL: "postgresql+asyncpg://postgres:niko1234@postgres:5432/ai_worker_db"
    build:
      context: ./ai-worker
      dockerfile: Dockerfile
    volumes:
      - "D:/ai-worker-store/model/my-final-toxic-model:/app/models/my-final-toxic-model"
      - "D:/ai-worker-store/cache:/app/.hf_cache"
    depends_on:
      postgres:
        condition: service_healthy

  background_job_worker:
    container_name: background_job_worker
    build:
      context: .
      dockerfile: ./background-job-worker/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    container_name: postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: niko1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./script/init-db.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: redis-server
    image: redis
    restart: always
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  rabbitmq_data:
  rabbitmq_log:
  redis_data:
  platform_core_upload:
  message_service_upload: