// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using platform_core_service.Data;

#nullable disable

namespace platform_core_service.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260502120000_AddProfileSuspension")]
    partial class AddProfileSuspension
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.13");
#pragma warning restore 612, 618
        }
    }
}
