export enum NotificationEventEnum {
  // Voting
  UPVOTE_POST = 0,
  DOWNVOTE_POST = 1,
  UPVOTE_ANSWER = 2,
  DOWNVOTE_ANSWER = 3,
  UPVOTE_COMMENT = 4,
  DOWNVOTE_COMMENT = 5,
  UPVOTE_QUESTION = 6,
  DOWNVOTE_QUESTION = 7,

  // Q&A
  NEW_ANSWER = 8,
  COMMENT_POST = 9,
  COMMENT_ANSWER = 10,
  REPLY_COMMENT = 11,
  ANSWER_ACCEPTED = 12,

  // Follow
  FOLLOW_USER = 13,
  FOLLOW_REQUEST = 14,
  FOLLOW_ACCEPTED = 15,

  // Community
  COMMUNITY_INVITE = 16,
  COMMUNITY_JOIN_REQUEST = 17,
  COMMUNITY_POST = 18,
  COMMUNITY_ROLE_CHANGE = 19,
  COMMUNITY_BAN = 20,

  // Messaging
  NEW_MESSAGE = 21,
  MESSAGE_REQUEST = 22,

  // System
  MODERATION_RESULT = 23,
  REPUTATION_MILESTONE = 24,
  SYSTEM_ANNOUNCEMENT = 25,
}

export enum EntityTypeEnum {
  POST = 0,
  QUESTION = 1,
  COMMENT = 2,
  ANSWER = 3,
  COMMUNITY = 4,
  PROFILE = 5,
  MESSAGE = 6,
}
