export enum NotificationEventEnum {
  // Voting
  UPVOTE_POST = 'UPVOTE_POST',
  DOWNVOTE_POST = 'DOWNVOTE_POST',
  UPVOTE_ANSWER = 'UPVOTE_ANSWER',
  DOWNVOTE_ANSWER = 'DOWNVOTE_ANSWER',
  UPVOTE_COMMENT = 'UPVOTE_COMMENT',
  DOWNVOTE_COMMENT = 'DOWNVOTE_COMMENT',

  // Q&A
  NEW_ANSWER = 'NEW_ANSWER',
  COMMENT_POST = 'COMMENT_POST',
  COMMENT_ANSWER = 'COMMENT_ANSWER',
  REPLY_COMMENT = 'REPLY_COMMENT',
  ANSWER_ACCEPTED = 'ANSWER_ACCEPTED',

  // Follow
  FOLLOW_USER = 'FOLLOW_USER',
  FOLLOW_REQUEST = 'FOLLOW_REQUEST',
  FOLLOW_ACCEPTED = 'FOLLOW_ACCEPTED',

  // Community
  COMMUNITY_INVITE = 'COMMUNITY_INVITE',
  COMMUNITY_JOIN_REQUEST = 'COMMUNITY_JOIN_REQUEST',
  COMMUNITY_POST = 'COMMUNITY_POST',
  COMMUNITY_ROLE_CHANGE = 'COMMUNITY_ROLE_CHANGE',
  COMMUNITY_BAN = 'COMMUNITY_BAN',

  // Messaging
  NEW_MESSAGE = 'NEW_MESSAGE',
  MESSAGE_REQUEST = 'MESSAGE_REQUEST',

  // System
  MODERATION_RESULT = 'MODERATION_RESULT',
  REPUTATION_MILESTONE = 'REPUTATION_MILESTONE',
  SYSTEM_ANNOUNCEMENT = 'SYSTEM_ANNOUNCEMENT',
}

export enum EntityTypeEnum {
  POST = 'POST',
  COMMENT = 'COMMENT',
  ANSWER = 'ANSWER',
  COMMUNITY = 'COMMUNITY',
  PROFILE = 'PROFILE',
  MESSAGE = 'MESSAGE',
}
